config/routes.rb
StoreEngine::Application.routes.draw do
  root to: 'products#index'

  get "/code" => redirect("http://github.com/raphweiner/store_engine")
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/login" => "sessions#new", :as => "login"
  get "/signup" => "users#new", :as => "signup"

  get "/account" => redirect("/account/profile")
  get "/account/profile" => "users#show"
  get "/account/orders" => "orders#index"
  get "/account/ratings" => "ratings#index"
  get "/account/orders/:id" => "orders#show", :as => "account_order"
  post "/buy_now" => "orders#buy_now", :as => 'buy_now'
  put "/i18n" => "i18n#update"

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :products, only: [ :index, :show ] do
    resources :ratings, except: [ :index, :show, :destroy ]
  end

  resource :cart, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  resources :users, only: [ :new, :create, :update ] do
    resources :orders, except: [ :show ]
  end

  namespace :admin do
    root to: redirect("/admin/dashboard")
    get :dashboard, to: "orders#index", as: 'dashboard'
    get :search, to: "orders#index", as: 'search'

    resources :sales, as: 'sales' do
      member do
        post :toggle_status
      end
    end

    resources :products do
      member do
        post :toggle_status
      end
    end

    resources :orders, only: [ :show, :update ]
    resources :order_items, only: [ :update, :destroy]
    resources :categories, except: [ :show ] do
      member do
        get :products
      end
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :session

  def initialize(session)
    @session = session
  end

  def items
    session.map do |id, quantity|
      CartItem.new(Product.find(id), quantity)
    end
  end

  def total
    items.map { |item| item.total }.inject(&:+)
  end

  def remove_item(remove_item_param)
    if id = remove_item_param[:product_id]
      session.delete(id)
    end
    session
  end

  def update(carts_param)
    if id = carts_param[:product_id]
      quantity = carts_param[:quantity]
      session[id] = quantity || (session[id].to_i + 1).to_s
    end
    session
  end

  def destroy
    session = {}
  end

  def count
    session.present? ? "(#{calculate_count})" : nil
  end

  def empty?
    items.empty?
  end

private
  def calculate_count
    session.values.map(&:to_i).reduce(&:+)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :find_or_create_cart

  def show
    session[:return_to] = request.fullpath
  end

  def update
    session[:cart] = current_cart.update(params[:carts])
    redirect_to(:back)
  end

  def remove_item
    session[:cart] = current_cart.remove_item(params[:remove_item])
    redirect_to(:back)
  end

  def destroy
    session[:cart] = current_cart.destroy
    redirect_to root_path, :notice  => "Cart cleared."
  end
end

app/views/carts/_cart_item.html.erb
<% current_cart.items.each do |cart_item| %>
<tr id="product_<%= cart_item.product.id %>">
  <td><%= image_tag cart_item.product.image_path, class: 'cart-item' %></td>
  <td>
    <%= link_to cart_item.title, product_path(cart_item.product) %>
    <br>
    <%= cart_item.product.description %>
    <br>
    <%= link_to t('action.remove'), remove_item_cart_path(remove_item: { product_id: cart_item.product.id }), confirm: t('confirm'), method: :put %>
  </td>
  <td><%= number_to_currency(cart_item.unit_price) %></td>
  <td><%= cart_item.percent_off %> %</td>
  <td><%= number_to_currency(cart_item.selling_price) %></td>
  <td>
    <%= simple_form_for :carts, url: '/cart', method: :put do |f| %>
      <%= f.hidden_field :product_id, value: cart_item.product.id %>
      <%= f.input_field :quantity, value: cart_item.quantity, class: 'span1' %>
      <%= f.button :submit, t('crud.update'), class:'btn btn-info' %>
    <% end %>
  </td>
</tr>
<% end %>

app/views/carts/_checkout_button.html.erb
<% if current_user %>
  <%= form_tag user_orders_path(current_user) do %>
    <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
            data-key="pk_test_osSOH0LyEEACshdRsLjyvGSz"
            data-image="/assets/marcy_stripe.png"
            data-name="<%= t('store.name') %>"
            data-description="<%= t('purchase') %>"
            data-label="<%= t('checkout') %>"
            data-amount="<%= price * 100 %>">
    </script>
  <% end %>
<% else %>
  <%= button_to t('checkout'), login_path, class: 'btn btn-custom-lighten', method: :get %>
<% end %>

app/views/carts/show.html.erb
<div class="cart-overview">
  <% if current_cart.empty? %>
      <h5><%= t('cart.isempty') %></h5>
      <%= link_to t('back.home'), root_path %>
  <% else %>
      <table class="table table-striped">
        <thead>
        <th></th>
        <th><%= t('product.self') %></th>
        <th><%= t('product.originalprice') %></th>
        <th><%= t('product.discount') %></th>
        <th><%= t('product.price') %></th>
        <th><%= t('product.quantity') %></th>
        </thead>
        <tbody>
        <%= render partial: 'cart_item' %>
        </tbody>
      </table>

      <div id="shopping_cart_summary">
        <h5>Total: <%= number_to_currency(current_cart.total) %></h5>
        <%= render partial: 'checkout_button',
                   locals: { price: current_cart.total } %>
        <%= button_to t('cart.empty'), cart_path, class: 'btn btn-warning', method: :delete %>
      </div>
  <% end %>
</div>