config/routes.rb
StoreEngine::Application.routes.draw do
  root to: 'products#index'

  get "/code" => redirect("http://github.com/raphweiner/store_engine")
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/login" => "sessions#new", :as => "login"
  get "/signup" => "users#new", :as => "signup"

  get "/account" => redirect("/account/profile")
  get "/account/profile" => "users#show"
  get "/account/orders" => "orders#index"
  get "/account/ratings" => "ratings#index"
  get "/account/orders/:id" => "orders#show", :as => "account_order"
  post "/buy_now" => "orders#buy_now", :as => 'buy_now'
  put "/i18n" => "i18n#update"

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :products, only: [ :index, :show ] do
    resources :ratings, except: [ :index, :show, :destroy ]
  end

  resource :cart, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  resources :users, only: [ :new, :create, :update ] do
    resources :orders, except: [ :show ]
  end

  namespace :admin do
    root to: redirect("/admin/dashboard")
    get :dashboard, to: "orders#index", as: 'dashboard'
    get :search, to: "orders#index", as: 'search'

    resources :sales, as: 'sales' do
      member do
        post :toggle_status
      end
    end

    resources :products do
      member do
        post :toggle_status
      end
    end

    resources :orders, only: [ :show, :update ]
    resources :order_items, only: [ :update, :destroy]
    resources :categories, except: [ :show ] do
      member do
        get :products
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :description, :price, :status, :category_ids, :image_path
  has_and_belongs_to_many :categories

  validates :title, presence: :true,
                    uniqueness: { case_sensitive: false }
  validates :description, presence: :true
  validates :status, presence: :true,
                     inclusion: { in: %w(active retired) }
  validates :price, presence: :true,
                    format: { with: /^\d+??(?:\.\d{0,2})?$/ },
                    numericality: { greater_than: 0 }

  scope :by_recency, order('created_at desc')
  scope :active, where(status: 'active')
  scope :for_term, lambda { |term|
      where("lower(title) LIKE ? OR lower(description) LIKE ?", "%#{term.downcase}%", "%#{term.downcase}%")
  }

  def toggle_status
    if status == 'active'
      update_attributes(status: 'retired')
    elsif status == 'retired'
      update_attributes(status: 'active')
    end
  end

  def on_sale?
    percent_of_original.to_i != 1
  end

  def current_price
    sale_price
  end

  def sale_price
    price - discount
  end

  def discount
    price * (1 - percent_of_original)
  end

  def percent_off
    (1 - percent_of_original) * 100
  end

  def percent_of_original
    if category_ids.present?
      percent_of_category = category_sales.map do |category_sale|
        (100 - category_sale.percent_off) / BigDecimal.new('100')
      end.inject(BigDecimal.new('1')) do |memo, percent_of_total|
        memo = memo * percent_of_total
        memo
      end
    end
    if category_ids.present?
      percent_of_product * percent_of_category
    else
      percent_of_product
    end
  end

  def product_sales
    Sale.where(group: 'product').
         where(status: 'active').
         where(foreign_key: self.id)
  end

  def percent_of_product
    sales_products = product_sales.map do |product_sale|
      (100 - product_sale.percent_off) / BigDecimal.new('100')
    end

    sales_products.inject(BigDecimal.new('1')) do |memo, percent_of_total|
      memo = memo * percent_of_total
      memo
    end
  end

  def category_sales
    Sale.where(group: 'category')
        .where(status: 'active')
        .where(foreign_key: category_ids)
  end

  def thumbnail_path
    image_path.sub("stickers", "thumbnails") if image_path
  end

  def product_order_items_count
    OrderItem.find_all_by_product_id(self.id).count
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :require_admin

  def index
    @products = Product.by_recency.paginate(:page => (params[:page] || 1), :per_page => 24)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to admin_products_path,
        :notice => "Successfully created product."
    else
      render :action => 'new', :notice  => "Product creation failed."
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to admin_products_path,
        :notice  => "Successfully updated product."
    else
      render :action => 'edit', :notice  => "Update failed."
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_url,
      :notice => "Successfully destroyed product."
  end

  def toggle_status
    @product = Product.find(params[:id])
    if @product.toggle_status
      redirect_to admin_products_path,
        :notice  => "Product status successfully set to '#{@product.status}'."
    else
      head 400
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Search.filter_products(params)
    @categories = Category.all
  end

  def show
    session[:return_to] = request.fullpath
    @product = Product.find(params[:id])
    @ratings = Rating.where(product_id: params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def activate_or_retire_translation(status)
    { 'active' => t('product.retire'),
      'retired' => t('product.activate')
    }[status]
  end
end

app/views/products/_add_to_cart_button.html.erb
<%= simple_form_for :carts, url: cart_path, method: :put do |f| %>
  <%= f.hidden_field :product_id, value: product.id %>
  <%= f.button :submit, t('cart.add'), class: 'btn btn-custom-lighten' %>
<% end %>

app/views/products/_buy_now_button.html.erb
<% if logged_in? %>
  <%= form_tag buy_now_path, id: "buyNowForm" do %>
    <%= hidden_field_tag 'order', product.id.to_s %>
    <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
            data-key="pk_test_osSOH0LyEEACshdRsLjyvGSz"
            data-image="/assets/marcy_stripe.png"
            data-name="<%= t('store.name') %>"
            data-label="<%= t('product.buynow') %>"
            data-amount="<%= product.current_price * 100 %>">
    </script>

  <% end %>
<% else %>
  <%= button_to t('product.buynow'), login_path, class: 'btn btn-primary', method: :get %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product) do %>
  <div class="products span2">
    <p><%= image_tag product.thumbnail_path %></p>
    <h5><%= product.title.titleize %>&nbsp;(<%= product.product_order_items_count %>)</h5>
    <% if product.on_sale? %>
      <p id="onsale"><b><%= t('product.onsale') %></b></p>
      <p id="saleprice"><%= t('product.saleprice') %>: <%= number_to_currency(product.sale_price) %></p>
    <% else %>
      <p><%= t('product.price') %>: <%= number_to_currency(product.price) %></p>
    <% end %>
  </div>
<% end %>

app/views/products/_rating.html.erb
<div class='rating'>
  <div class="rating-title">
    <div id="star-rating<%=rating.id%>">
      <b><%= rating.title %> </b>
    </div>
  </div>
  <p><%= rating.body %></p>
  <p><%= t('ratings.displayname') %>: <%= rating.user.display_name %></p>
</div>

<script>
  $('#star-rating<%=rating.id%>').raty({ readOnly: true, score: <%= rating.stars %> });
</script>

app/views/products/_user_rating_status_or_action.html.erb
<% if current_user && user_purchased?(current_user, @product) %>
  <% if rating = user_rating(current_user, @ratings) %>
    <% if rating.editable? %>
      <%= button_to t('ratings.rated.edit'), edit_product_rating_path(@product, rating), method: :get, class: 'btn btn-warning' %>
    <% end %>
  <% else %>
    <p><%= t('ratings.pleaserate') %></p>
    <%= button_to t('ratings.rateit'), new_product_rating_path(@product), class: 'btn btn-custom-lighten', method: :get %>
  <% end %>
<% end %>

app/views/products/index.html.erb
<div class="product-index">
  <section class="row">
      <div class="btn-group span1" id="homepage-category-dropdown">
        <a class="btn btn-custom-lighten dropdown-toggle" data-toggle="dropdown" href="#">
          <%= t 'categories.select' %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="/">Show All</a></li>
          <% unless @categories.nil? %>
              <% @categories.each do |category| %>
                  <li>
                    <%=link_to "#{category.title} (#{category.products.length})", products_path(category_id: category.id) %>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </div>

      <form action="<%= products_path %>" method="get" class="form-search">
        <input type="text" id="product-search" value="<%= params[:search] %>" name="search" class="input-medium search-query">
        <button type="submit" class="btn btn-custom-lighten"><%= t 'navigation.search' %></button>
      </form>
  </section>

  <br/>

  <div id="product_listing" class="row-fluid">
    <%= render @products %>
  </div>

  <%= will_paginate @products %>

</div>

app/views/products/show.html.erb
<div class="row">
  <div class="prod_detail_img span6">
    <p><%= image_tag @product.image_path %></p>
  </div>
  <div class="prod_detail_text span6">
    <h2><% t('product.title') %><%= @product.title %></h2>
    <h3>Sales for this thing: <% t('product.product_order_items_count') %><%= @product.product_order_items_count %></h3>
    <p><% t('product.description') %><%= @product.description %></p>
    <div id="product-categories">
      <b><%= t('categories.self') %>:</b>
      <% @product.categories.each do |category| %>
          <a href='/products/?category_id=<%= category.id %>'><span class="label"><%= category.title %></span></a>
      <% end %>
    </div>
    <br>
    <% if @product.on_sale? %>
      <p><b><%= t('product.onsale') %></b></p>
      <p><%= t('product.originalprice') %>: <strike><%= number_to_currency(@product.price) %></strike></p>
      <p><%= t('product.percentsavings') %>: <%= @product.percent_off %>%</p>
      <p><%= t('product.saleprice') %>: <%= number_to_currency(@product.sale_price) %></p>
    <% else %>
      <p><%= t('product.price') %>: <%= number_to_currency(@product.price) %></p>
    <% end %>
    <% if @product.status == 'active' %>
      <%= render partial: 'add_to_cart_button', locals: {product: @product} %>
      <%= render partial: 'buy_now_button', locals: {product: @product} %>
    <% else %>
      <p> Product is retired! </p>
    <% end %>
    <%= render 'user_rating_status_or_action' %>
    <% if @ratings.present? %>
        <div class="average-rating">
          <h4><%= t('ratings.average') %>: </h4>
          <div id="star-avg">
            <script>
                $('#star-avg').raty({ readOnly: true, score: <%= average_rating(@ratings) %> });
            </script>
          </div>
          <p></p>
        </div>
        <%= render partial: 'rating', collection: @ratings %>
    <% else %>
        <%= t('ratings.none') %>
    <% end %>
  </div>
</div>