config/routes.rb
StoreEngine::Application.routes.draw do
  root to: 'products#index'

  get "/code" => redirect("http://github.com/raphweiner/store_engine")
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/login" => "sessions#new", :as => "login"
  get "/signup" => "users#new", :as => "signup"

  get "/account" => redirect("/account/profile")
  get "/account/profile" => "users#show"
  get "/account/orders" => "orders#index"
  get "/account/ratings" => "ratings#index"
  get "/account/orders/:id" => "orders#show", :as => "account_order"
  post "/buy_now" => "orders#buy_now", :as => 'buy_now'
  put "/i18n" => "i18n#update"

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :products, only: [ :index, :show ] do
    resources :ratings, except: [ :index, :show, :destroy ]
  end

  resource :cart, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  resources :users, only: [ :new, :create, :update ] do
    resources :orders, except: [ :show ]
  end

  namespace :admin do
    root to: redirect("/admin/dashboard")
    get :dashboard, to: "orders#index", as: 'dashboard'
    get :search, to: "orders#index", as: 'search'

    resources :sales, as: 'sales' do
      member do
        post :toggle_status
      end
    end

    resources :products do
      member do
        post :toggle_status
      end
    end

    resources :orders, only: [ :show, :update ]
    resources :order_items, only: [ :update, :destroy]
    resources :categories, except: [ :show ] do
      member do
        get :products
      end
    end
  end
end

app/views/layouts/_logout_button.html.erb
<% if session[:cart] && !session[:cart].empty? %>
  <%= link_to t('navigation.logout'), session_path(current_user), method: :delete, confirm: t('cart.confirmlogout') %>
<% else %>
  <%= link_to t('navigation.logout'), session_path(current_user), method: :delete %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="logo">
  <%= link_to(image_tag('marcy_logo.png'), root_path, :class => 'brand') %>
</div>
<div class="logo-text">
  <%= link_to t('store.name'), root_path, :class => 'brand' %>
</div>
<div class="nav-buttons">
  <ul class="nav pull-right">
    <% if logged_in? && current_user.admin? %>
    <li><%= link_to t('admin.self'), admin_dashboard_path %></li>
    <% end %>

    <% if logged_in? %>
        <li><%= render 'layouts/logout_button' %></li>
        <li><%= link_to t('navigation.account'), account_path %></li>
    <% else %>
        <li><%= link_to t('navigation.login'), login_path  %></li>
        <li><%= link_to t('navigation.signup'), signup_path %></li>
    <% end %>
    <li>
      <%= button_to "#{t 'navigation.cart'} #{current_cart.count}", cart_path, class: 'btn btn-custom-lighten', method: :get %>
    </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag("/images/flags/#{get_flag}.png") %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to image_tag("/images/flags/us.png") + " #{t('languages.english')}", i18n_path(locale: 'en'), method: :put %></li>
      <li><%= link_to image_tag("/images/flags/cs.png") + " #{t('languages.creaturespeak')}", i18n_path(locale: 'cs'), method: :put %></li>
      <li><%= link_to image_tag("/images/flags/fr.png") + " #{t('languages.french')}", i18n_path(locale: 'fr'), method: :put %></li>
      <li><%= link_to image_tag("/images/flags/ca.png") + " #{t('languages.canadian')}", i18n_path(locale: 'ca'), method: :put %></li>
    </ul>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t('store.name') %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag "/favicon.ico?1" %>
    <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div> <!--! end of content-->
        <div id="footer">
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>